#!/bin/sh

#xclock &
#xeyes &
#sleep 2 && xterm &

xfce4-terminal &
onboard &

if [ -z "$VALGRIND" ]
  then exec "$(dirname "$(realpath "$0")")/bin/dpaw"
  else exec valgrind --leak-check=full "$(dirname "$(realpath "$0")")/bin/dpaw"
fi
