#ifndef ATOM_ICCCM_H
#define ATOM_ICCCM_H

#define ATOMS \
  X(WM_PROTOCOLS) \
  X(WM_NAME) \
  X(WM_ICON_NAME) \
  X(WM_NORMAL_HINTS) \
  X(WM_SIZE_HINTS) \
  X(WM_HINTS) \
  X(WM_ICON_SIZE) \
  X(WM_CLASS) \
  X(WM_TRANSIENT_FOR) \
  X(WM_TAKE_FOCUS) \
  X(WM_SAVE_YOURSELF) \
  X(WM_DELETE_WINDOW) \
  X(WM_COLORMAP_WINDOWS) \
  X(WM_CLIENT_MACHINE) \
  X(WM_STATE) \
  X(WM_CHANGE_STATE) \
  X(WM_COLORMAP_NOTIFY) \
  X(WM_COMMAND)

#include <-dpaw/atom.template>

#endif
