#!/bin/sh

#xclock &
#xeyes &
#sleep 2 && xterm &

xprop -root -remove AT_SPI_BUS
/usr/lib/at-spi2-core/at-spi-bus-launcher &

xfce4-terminal &

export ASAN_OPTIONS=abort_on_error=1

project_root="$(dirname "$(realpath "$0")")"

export DPAW_PLUGIN_PATH="$project_root/bin/plugin/"

if [ -z "$VALGRIND" ]
  then exec "$project_root/bin/dpaw"
  else exec valgrind --leak-check=full --show-leak-kinds=all --suppressions="$project_root/dpaw.supp" "$project_root/bin/dpaw"
fi
