#include <xev/X.c>
#include <dpawindow/root.h>
#include <screenchange.h>
#include <workspace.h>
#include <dpaw.h>
#include <stdio.h>
#include <stdlib.h>

DEFINE_DPAW_DERIVED_WINDOW(root)

int dpawindow_root_init(struct dpaw* dpaw, struct dpawindow_root* window){
  for(struct xev_event_extension* extension=dpaw_event_extension_list; extension; extension=extension->next){
    if(extension->init(dpaw, extension)){
      fprintf(stderr, "Failed to initialise event extension %s\n", extension->name);
      if(extension->required)
        return -1;
      continue;
    }
    extension->initialised = true;
  }
  if(dpawindow_root_init_super(dpaw, window) != 0){
    fprintf(stderr, "dpawindow_root_init_super failed\n");
    return -1;
  }
  if(dpaw_screenchange_init(&window->screenchange_detector, dpaw)){
    fprintf(stderr, "dpaw_screenchange_init failed\n");
    return -1;
  }
  if(dpaw_workspace_manager_init(&window->workspace_manager, dpaw) == -1){
    fprintf(stderr, "dpaw_workspace_init failed\n");
    return -1;
  }
  return 0;
}

int dpawindow_root_cleanup(struct dpawindow_root* window){
  dpaw_workspace_manager_destroy(&window->workspace_manager);
  dpaw_screenchange_destroy(&window->screenchange_detector);
  return 0;
}

EV_ON(root, MapRequest){
  if(dpaw_workspace_manager_manage_window(&window->workspace_manager, event->window) != 0)
    return EHR_ERROR;
  return EHR_OK;
}

EV_ON(root, UnmapNotify){
  extern struct dpawindow_type dpawindow_type_app;
  struct dpawindow* win = dpawindow_lookup(window->window.dpaw, event->window);
  if(!win)
    return EHR_NEXT;
  if(win->type == &dpawindow_type_app){
    // An application is supposed to send this request manually
    // Regular unmap requests are also generated by this window manager, but shouldn't be handled here.
    if(!event->send_event)
      return EHR_NEXT;
    if(dpaw_workspace_manager_abandon_window((struct dpawindow_app*)win))
      return EHR_ERROR;
    return EHR_OK;
  }
  return EHR_NEXT;
}

EV_ON(root, DestroyNotify){
  extern struct dpawindow_type dpawindow_type_app;
  struct dpawindow* win = dpawindow_lookup(window->window.dpaw, event->window);
  if(!win)
    return EHR_NEXT;
  if(win->type == &dpawindow_type_app){
    if(dpaw_workspace_manager_abandon_window((struct dpawindow_app*)win))
      return EHR_ERROR;
    return EHR_OK;
  }
  return EHR_NEXT;
}

EV_ON(root, ConfigureRequest){
  printf("ConfigureRequest %lu\n", event->window);
  XWindowChanges changes = {
    .x = event->x,
    .y = event->y,
    .width  = event->width,
    .height = event->height,
    .border_width = event->border_width,
    .sibling      = event->above,
    .stack_mode   = event->detail
  };
  XConfigureWindow(window->display, event->window, event->value_mask, &changes);
  return EHR_OK;
}

EV_ON(root, ReparentNotify){
  (void)window;
  printf("ReparentNotify %lu\n", event->window);
  return EHR_OK;
}

