#include <xev/X.c>
#include <dpawindow/root.h>
#include <screenchange.h>
#include <workspace.h>
#include <dpawin.h>
#include <stdio.h>
#include <stdlib.h>

DEFINE_DPAWIN_DERIVED_WINDOW(root)

int dpawindow_root_init(struct dpawin* dpawin, struct dpawindow_root* window){
  dpawin->root.xev_list = calloc(dpawin_event_extension_count, sizeof(*dpawin->root.xev_list));
  if(!dpawin->root.xev_list){
    perror("calloc failed");
    goto error;
  }
  for(const struct xev_event_extension* extension=dpawin_event_extension_list; extension; extension=extension->next){
    struct dpawin_xev* xev = &dpawin->root.xev_list[extension->extension_index];
    xev->extension = -2; // Sentinel to check if initialisation worked properly. -1 is alredy used for the X fake extension
    if(extension->init(dpawin, xev)){
      fprintf(stderr, "Failed to initialise event extension %s\n", extension->name);
      if(extension->required)
        goto error;
      continue;
    }
    xev->xev = extension;
  }
  if(dpawindow_root_init_super(dpawin, window) != 0){
    fprintf(stderr, "dpawindow_root_init_super failed\n");
    goto error;
  }
  if(dpawin_screenchange_init(&window->screenchange_detector, window->display)){
    fprintf(stderr, "dpawin_screenchange_init failed\n");
    goto error;
  }
  if(dpawin_workspace_manager_init(&window->workspace_manager, dpawin) == -1){
    fprintf(stderr, "dpawin_workspace_init failed\n");
    goto error;
  }
  return 0;
error:
  if(dpawin->root.xev_list)
    free(dpawin->root.xev_list);
  return -1;
}

int dpawindow_root_cleanup(struct dpawindow_root* window){
  dpawin_workspace_manager_destroy(&window->workspace_manager);
  return 0;
}

EV_ON(root, MapRequest){
  if(dpawin_workspace_manager_manage_window(&window->workspace_manager, event->window) != 0)
    return EHR_ERROR;
  return EHR_OK;
}

EV_ON(root, UnmapNotify){
  extern struct dpawindow_type dpawindow_type_app;
  struct dpawindow* win = dpawindow_lookup(window->window.dpawin, event->window);
  if(!win)
    return EHR_NEXT;
  if(win->type == &dpawindow_type_app){
    // An application is supposed to send this request manually
    // Regular unmap requests are also generated by this window manager, but shouldn't be handled here.
    if(!event->send_event)
      return EHR_NEXT;
    if(dpawin_workspace_manager_abandon_window((struct dpawindow_app*)win))
      return EHR_ERROR;
    return EHR_OK;
  }
  return EHR_NEXT;
}

EV_ON(root, DestroyNotify){
  extern struct dpawindow_type dpawindow_type_app;
  struct dpawindow* win = dpawindow_lookup(window->window.dpawin, event->window);
  if(!win)
    return EHR_NEXT;
  if(win->type == &dpawindow_type_app){
    if(dpawin_workspace_manager_abandon_window((struct dpawindow_app*)win))
      return EHR_ERROR;
    return EHR_OK;
  }
  return EHR_NEXT;
}

EV_ON(root, ConfigureRequest){
  XWindowChanges changes = {
    .x = event->x,
    .y = event->y,
    .width  = event->width,
    .height = event->height,
    .border_width = event->border_width,
    .sibling      = event->above,
    .stack_mode   = event->detail
  };
  XConfigureWindow(window->display, event->window, event->value_mask, &changes);
  return EHR_OK;
}

EV_ON(root, ReparentNotify){
  (void)window;
  printf("ReparentNotify %lu\n", event->window);
  return EHR_OK;
}

